name: QRohlf.com
description: A blog about startups, technology, and other interesting things.
url: http://qrohlf.com
permalink: /posts/:title
markdown: redcarpet
future: true
poole:
    word_separator: "-"
    auto_open: true
include: [".well-known"]
exclude: [compass.rb, config.ru, Gemfile, Gemfile.lock, Procfile, Rakefile, Read.md, sass, unicorn.rb, vendor]