name: QRohlf.com
description: A blog about startups, technology, and other interesting things.
url: http://qrohlf.com
markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]