name: QRohlf.com
description: A blog about startups, technology, and other interesting things.
url: http://qrohlf.com
markdown: rdiscount
pygments: true
permalink: /posts/:title
exclude: [bourbon, neat, main.scss, README.md, Gemfile, Gemfile.lock]
rdiscount:
  extensions: [smart]
